### ISSUE TITLE
MATLAB:unassignedOutputs when loading fails in splatt_load

### ISSUE THREAD

**Issue by nvervliet** [ShadenSmith/splatt#17]
The command 
```
X = splatt_load('mytensor.tns');
```
throws an `MATLAB:unassignedOutputs` exception when the tensor cannot be loaded, e.g., because the file is not found. I suggest to either throw a "file not found" exception, or to return an empty tensor. (Probably the former is preferable.)

**Comment by ShadenSmith** [comment]
This should be fixed now. I use `mexErrMsgIdAndText()` to print an error with ID `SPLATT:FileNotFound` and then abort the MEX execution.

SPLATT also prints an error message to `STDERR`, but I think that will only be displayed if you are running Matlab without a GUI? An unfortunate side effect is that you now get two error messages when running without a GUI.
