### ISSUE TITLE
Static TLS problem in Matlab 

### ISSUE THREAD

**Issue by nvervliet** [ShadenSmith/splatt#19]
Running `splatt_load` (and probably any other splatt function as well), results in a static TLS error:
```
dlopen: cannot load any more object with static TLS
```
(On a Ubuntu 14.04 system with Matlab 2016b.)

I traced the error back to the openMPI library used. There seem to be two solutions to mitigate this problem:
1. Add a spatt command as the first line in your `startup.m` file. This way the library is loaded soon enough.
2. Alternatively, you can load matlab as follows
    ```
    LD_PRELOAD=libgomp.so.1 matlab 
    ````
    or 
    ```
    export LD_PRELOAD=libgomp.so.1
    matlab
    ```
The latter export function can be put in your `.bashrc` file (or equivalent). 
Both approaches seemed to work for me. The former approach is somewhat messy and will always load SPLATT. The latter approach made loading MATLAB extremely slow (couple of minutes). This can be a licensing error though.

**Comment by ShadenSmith** [comment]
Thanks for looking into this, Nico. I added one more solution, which is to simply disable OpenMP. This is the least preferable option, as OpenMP is what gives us multi-threading, but I suppose is the easiest.

I agree with you that the `LD_PRELOAD` is the cleanest option.

When you have a moment, could you try out `./configure --blas-int=64 --no-openmp`? The static TLS issue does not occur on my machine, so I cannot test it myself.

**Comment by nvervliet** [comment]
Disabling OpenMP seems to work without the `LD_PRELOAD` option.

**Comment by ShadenSmith** [comment]
Thanks for looking into it. `README.md` has been updated based on your suggestions.
