### ISSUE TITLE
splatt_cpd throws segmentation fault in matlab for nips.tns

### ISSUE THREAD

**Issue by nvervliet** [ShadenSmith/splatt#21]
Consider a basic CPD of a tensor using the matlab interface:
```
X = splatt_load('mytensor.tns');
U = splatt_cpd(X, 5);
```
If we choose `mytensor.tns` to be the example given in the readme.md file, everything works well. If we choose the `nips.tns` file from [frostt-tensor](https://github.com/frostt-tensor/frostt-tensor.github.io/blob/master/_tensors/nips.md) instead, `splatt_cpd` throws a segmentation fault. (`splatt_load` works fine). I haven't tested the C interface.

**Comment by nvervliet** [comment]
It seems that 
```
U = splatt_cpd('nips.tns', 5);
```
does work. I guess the problem is situated in passing the matlab structure to C.

**Comment by ShadenSmith** [comment]
Thanks again! I had added some fields to the CSF structure and forgot to update the MEX conversion.
