### ISSUE TITLE
Minor issue

### ISSUE THREAD

**Issue by fruitfly1026** [ShadenSmith/splatt#28]
Inconsistency in the example of README file and the website example, "splatt_csf_t" and "splatt_kruskal_t" you mean"splatt_csf" and "splatt_kruskal" I think. No "cpd_opts" in the website example, "splatt_opts".

**Comment by ShadenSmith** [comment]
Thanks! The website should be fixed now. Really the whole website needs work and I need to include documentation using all of the doxygen in place. I am internally working on a major release that will include a better API and much better documentation!
