### ISSUE TITLE
Fits bigger than 1000

### ISSUE THREAD

**Issue by zahrarah** [ShadenSmith/splatt#33]
Hi,
I have a 100000*100000*2 tensor which is sparse. I have used splatt to factorize it but I have got fits more than 1000. Could you please help me? I always thought that fits have to be less than one. How can I solve this?
thanks in advance

**Comment by zahrarah** [comment]
the size of tensor is (100000 * 100000 * 2)

**Comment by ShadenSmith** [comment]
Hello,

Thank you for your interest in splatt! Very bad fits _can_ show as more than 1, but this is usually a sign of something wrong or data which does not have underlying tensor structure.

Can you show me the command you use to run splatt, and what the output is?

Also, can you show me the output of the following command:

```
$ splatt check <yourtensorfile> --fix=fixed.tns
```

This will tell us if there are duplicate non-zeros or empty slices in the tensor. If so, it will remove them and store it in a new tensor called `fixed.tns`.

Lastly, feel free to share the data with me to debug myself (if you are able to). You can email me a link to [shaden@cs.umn.edu](shaden@cs.umn.edu).
