### ISSUE TITLE
Segmentation fault in tucker decomposition

### ISSUE THREAD

**Issue by z-rahimi** [ShadenSmith/splatt#37]
Hi,

[logs.zip](https://github.com/ShadenSmith/splatt/files/4762810/logs.zip)

I got the following error when run ./configure --with-mpi && make in  my ubuntu 16.04 terminal:  
"In function ‘splatt_mpi_cpd_cmd’:
/home/zrahimi/splatt-tucker/src/cmds/mpi_cmd_cpd.c:247:35: error: ‘CSF_SORTED_MINUSONE’ undeclared (first use in this function)
       csf_alloc_mode(tt_filtered, CSF_SORTED_MINUSONE, m, csf+m, args.opts);
                                   ^
/home/zrahimi/splatt-tucker/src/cmds/mpi_cmd_cpd.c:247:35: note: each undeclared identifier is reported only once for each function it appears in".
 I think it is returning to csf.h which "CSF_SORTED_MINUS_ONE" is not declared in typedefs. I added  "CSF_SORTED_MINUSONE" to "./src/csf.h" and the make was done without error. 
In the main Splatt repository "CSF_SORTED_MINUSONE" exists in "csf.h" but in the tucker branch, it does not.  But after I run "./splatt tucker --alloc=greedy  ./tests/med5.tns" I got a "segmentation fault" error. The logfiles for --alloc=iter and alloc=greedy are attached.

Thanks in advance

**Comment by ShadenSmith** [comment]
Hello! I have not adapted the new Tucker code to MPI and certainly broke some MPI things along the way as you can see :-). It should work if you configure without `--with-mpi`.

**Comment by z-rahimi** [comment]
Thank you. I run without --with-mpi but the segmentation fault remains. This is the output for --alloc=iter:
Splatt v2.0.0 built from d0b6fb2-tucker

Tensor information ---------------------------------------------
FILE=./tests/tensors/med5.tns
DIMS=60114x83826x23034x1132x100 NNZ=100000 DENSITY=7.610792e-15
COORD-STORAGE=4.58MB

MAX_CSF=2
CSF_ALLOC_POLICY=ITER

    CSF:  0.018s
mode: 0 depth: 0
    CSF:  0.045s
mode: 1 depth: 0
    CSF:  0.009s
mode: 2 depth: 0
    CSF:  0.006s
mode: 3 depth: 0
    CSF:  0.004s
mode: 4 depth: 0
  its =   1 (4.456s)  fit = 0.00000  delta = +0.0000e+00
    CSF:  0.015s
mode: 0 depth: 0
    CSF:  0.016s
mode: 1 depth: 0
    CSF:  0.009s
mode: 2 depth: 0
    CSF:  0.006s
mode: 3 depth: 0
    CSF:  0.004s
mode: 4 depth: 0
  its =   2 (4.360s)  fit = 0.00000  delta = +0.0000e+00
Segmentation fault (core dumped)

**Comment by ShadenSmith** [comment]
Ah, you're totally right. Let me look into this and will get back to you!

**Comment by ShadenSmith** [comment]
Hi @z-rahimi , I just pushed some code that should fix this bug. Please re-open if you experience any issues!

I recommend testing with tensors from [frostt](http://frostt.io/tensors/). The tensors in the `tests/` directory are mostly noise for simple correctness testing, and so convergence and performance will look weird with them.

**Comment by ShadenSmith** [comment]
Also, there's a bit more in the codebase than I have published outside my thesis. If you are interested, there's an extra subsection in the Tucker chapter on reconstructing CSFs (that is the `--alloc=iter` option). It's best for higher-order tensors, but for 3D the `greedy` with the default 2 allocations is recommended.
