### ISSUE TITLE
Undefined reference that occurred in C/C++ API

### ISSUE THREAD

**Issue by vincenttsai2015** [ShadenSmith/splatt#38]
Hi,

I am going to implement parallelized tensor decomposition. When I tried the C/C++ API, I found there are several issues:
1. When I tried the example with the examples for C/C++ API, I found there is no type "splatt_csf_t" and "splatt_kruskal_t":
The example should be modified as follows: 

#include <splatt.h>
int main()

{
    
    /* allocate default options */
    double * cpd_opts = splatt_default_opts();
    
    /* load the tensor from a file */
    int ret;
    splatt_idx_t nmodes;
    splatt_csf * tt; //not "splatt_csf_t"!
    ret = splatt_csf_load("mytensor.tns", &nmodes, &tt, cpd_opts);

    /* do the factorization! */
    splatt_kruskal factored; //not "splatt_kruskal_t"!
    ret = splatt_cpd_als(tt, 10, cpd_opts, &factored);

    /* do some processing */
    for(splatt_idx_t m = 0; m < nmodes; ++m) {
        /* access factored.lambda and factored.factors[m] */
    }

    /* cleanup */
    splatt_free_csf(tt, cpd_opts);
    splatt_free_kruskal(&factored);
    splatt_free_opts(cpd_opts);

}

2. After modifying the code as above, I found there are "undefined reference" errors:
`/tmp/cc8AfqHz.o: In function main:
`splatt_example.cpp:(.text+0xc): undefined reference to splatt_default_opts
`splatt_example.cpp:(.text+0x29): undefined reference to splatt_csf_load
`splatt_example.cpp:(.text+0x48): undefined reference to splatt_cpd_als
`splatt_example.cpp:(.text+0x77): undefined reference to splatt_free_csf
`splatt_example.cpp:(.text+0x86): undefined reference to splatt_free_kruskal
`splatt_example.cpp:(.text+0x92): undefined reference to splatt_free_opts
`collect2: error: ld returned 1 exit status`

I'm wondering if there is some approach to fix the "undefined reference" issues. Thanks.

**Comment by vincenttsai2015** [comment]
I just figured out how to compile as follows: 
1. Need to add "-fopenmp" to invoke openmp.
2. Need to link libraries: libsplatt, liblapack and libblas
`g++ -std=c++11 -fopenmp splatt_example.cpp -lsplatt -llapack -lblas`
Thanks.

**Comment by ShadenSmith** [comment]
Hello! Thank you for your interest in SPLATT. I'm glad you got the build working. Apologies for the documentation mismatch -- would you consider submitting a PR with your recommended fix?
